SKILLS_CATALOG = [
    "Python", "JavaScript", "TypeScript", "Java", "Go", "Kotlin", "C#", "PHP",
    "Ruby", "Swift", "Rust", "Scala", "Elixir", "Dart", "R",
    "React", "Vue", "Angular", "Next.js", "Nuxt.js", "Svelte", "Flutter",
    "React Native", "Tailwind CSS",
    "Django", "FastAPI", "Flask", "Spring Boot", "Laravel", "Rails",
    "Express", "NestJS", "ASP.NET", "Gin",
    "Docker", "Kubernetes", "AWS", "Azure", "GCP", "Terraform",
    "Ansible", "Jenkins", "GitHub Actions", "GitLab CI",
    "Datadog", "Grafana", "Prometheus",
    "PostgreSQL", "MySQL", "MongoDB", "Redis", "Kafka",
    "Elasticsearch", "DynamoDB", "Cassandra", "RabbitMQ", "Celery",
    "Git", "CI/CD", "REST API", "GraphQL", "Microservices", "gRPC",
    "Linux", "Agile", "Scrum", "SQL", "NoSQL",
    "TensorFlow", "PyTorch", "scikit-learn", "pandas", "NumPy",
    "Spark", "Airflow", "dbt", "Power BI", "Tableau",
    "Machine Learning", "Deep Learning", "MLOps",
    "OAuth", "JWT",
]